// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-jeW0ZFQ4PEoUqDmaUh1JlbpeMtGfRk',
    appId: '1:434750096218:web:c40b3648128d24f68b6963',
    messagingSenderId: '434750096218',
    projectId: 'study-studio-783c8',
    authDomain: 'study-studio-783c8.firebaseapp.com',
    storageBucket: 'study-studio-783c8.firebasestorage.app',
    measurementId: 'G-38BGP4PMVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdc2EnLh5-g0YLMNeUINvm7EAQtYT5HXc',
    appId: '1:434750096218:android:c0ae9dce1c4587258b6963',
    messagingSenderId: '434750096218',
    projectId: 'study-studio-783c8',
    storageBucket: 'study-studio-783c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36IjBmQMPhtizSLvvZSzMHmgXWrhnd2s',
    appId: '1:434750096218:ios:3931390ad9915a148b6963',
    messagingSenderId: '434750096218',
    projectId: 'study-studio-783c8',
    storageBucket: 'study-studio-783c8.firebasestorage.app',
    iosBundleId: 'com.example.studystudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB36IjBmQMPhtizSLvvZSzMHmgXWrhnd2s',
    appId: '1:434750096218:ios:3931390ad9915a148b6963',
    messagingSenderId: '434750096218',
    projectId: 'study-studio-783c8',
    storageBucket: 'study-studio-783c8.firebasestorage.app',
    iosBundleId: 'com.example.studystudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk-jeW0ZFQ4PEoUqDmaUh1JlbpeMtGfRk',
    appId: '1:434750096218:web:99c8921e7a05bbcd8b6963',
    messagingSenderId: '434750096218',
    projectId: 'study-studio-783c8',
    authDomain: 'study-studio-783c8.firebaseapp.com',
    storageBucket: 'study-studio-783c8.firebasestorage.app',
    measurementId: 'G-35P47KQP1K',
  );

}